version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: some-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: events_db
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d events_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app-fastapi:
    build: .
    container_name: agenda_hub_fastapi
    volumes:
      - .:/app  # Mapeia a raiz (onde est√£o os scripts e a pasta /app)
    working_dir: /app
    profiles: ["fastapi"]
    ports:
      - "8000:8000"
    environment:
      APP_FRAMEWORK: fastapi
      DB_NAME: events_db
      DB_USER: user
      DB_PASSWORD: mysecretpassword
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
